#!/usr/bin/env bash

source "$(type -p hhs.bash)"
hhs_compatibility_check VERSION 0.1.0

function optparse_hello ()
{
  case "$1" in
    -b|--bold)
      # Put the name with the bold face.
      nparams 0
      optset BOLD "$1"
      ;;
    -n|--name) # NAME
      # Set a name.
      nparams 1
      optset NAME "$2"
      ;;
    *)
      return 1
      ;;
  esac
}

function hello () # [OPTIONS]
#   Say hello.
{
  local bold="${OPT_BOLD:+\e[1m}"
  local reset="${OPT_BOLD:+\e[0m}"
  echo -e "hello ${bold}${OPT_NAME:-hhs}${reset}."
}

invoke_command "$@"
