#!/usr/bin/env bash

source hhs.bash 0.2.0



# has_subcommand_sample=1 # uncomment if it has the subcommand.

function optparse_sample ()
{
  case "$1" in
    -o|--optional) # [OPTIONAL]
      # Can take a optional value. It's can be ommited.
      nparam 1 1
      optset OPTIONAL "default value"
      ;;
    -s|--switch) #
      # Have no values, only work as flag.
      nparam 0
      optset SWITCH "$1"
      ;;
    -v|--value) # VALUE
      # Always have a value
      nparam 1
      optset VALUE "$2"
      ;;
    *)
      return 1
      ;;
  esac
}

function sample() # [ARGS ...]
#   Descriptions
# Args:
#   ARGS : Arguments
{
  :
}



invoke_command "$@"
